---
title: "mapping"
author: "Gillian McGinnis"
date: "6/9/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggmap)
library(viridis)
```

```{r data_loading}
data_day <- read.csv("data/wrangled_new/wrangled_day.csv") %>% 
  filter(loc_tag != "Ogden84th") #filtering out the Vancouver data point
```

```{r get_map, eval = FALSE}
#
lat_min <- 45.4
#lat_max <- 45.65 #old val that would include the point in Vancouver
lat_max <- 45.6
long_min <- -122.854
long_max <- -122.58


pdx_box <- c(
  bottom = lat_min,
  top = lat_max,
  left = long_min,
  right = long_max
)

#avaialble maps: terrain, terrain-background, terrain-labels, terrain-lines, toner, toner-2010, toner-2011, toner-background, toner-hybrid, toner-labels, toner-lines, toner-lite, watercolor
pdx_map <- get_stamenmap(
  pdx_box,
  maptype = "toner-lite",
  zoom = 11
)

save(pdx_map, file = "data/maps/pdx_map.RData")

remove(lat_max, lat_min, long_max, long_min, pdx_box)
```

```{r date_range_inputs}
# pre
date_pre_start <- as.Date("2020-09-01")
date_pre_end <- as.Date("2020-09-09")
# during
date_fire_start <- as.Date("2020-09-10")
date_fire_end <- as.Date("2020-09-19")
# post
date_post_start <- as.Date("2020-09-20")
date_post_end <- as.Date("2020-09-29")

#names
facet_range <- c(
  "pre" = "Pre (Sep01-Sep09)",
  "fire" = "Fire (Sep10-Sep19)",
  "post" = "Post (Sep20-Sep29)"
)
```

```{r fire_map}
data_fire <- data_day %>% 
#data_day %>% 
  select(loc_tag, inout, ab, long, lat, date, `PM2.5_ATM_ug.m3`, `PM2.5_CF1_ug.m3`) %>% 
  rename(
    outside = `PM2.5_ATM_ug.m3`,
    inside = `PM2.5_CF1_ug.m3`
  ) %>% 
  pivot_longer(cols = c(outside, inside), names_to = "pm25_cat", values_to = "pm25") %>% 
  filter(inout == pm25_cat) %>% 
  select(!pm25_cat) %>% 
  filter(!(pm25 >= 1000)) %>% 
  group_by(loc_tag, inout, long, lat, date) %>% 
  summarise(pm_val = mean(pm25, na.rm = TRUE)) %>% 
  mutate(
    inout = factor(inout, levels = c("outside", "inside")),
    range = case_when(
      date >= date_pre_start & date <= date_pre_end ~ "pre",
      date >= date_fire_start & date <= date_fire_end ~ "fire",
      date >= date_post_start & date <= date_post_end ~ "post"
    ),
    range = factor(range, levels = c("pre", "fire", "post"))
  ) %>% 
  drop_na(range) %>% 
  group_by(loc_tag, inout, long, lat, range) %>% 
  summarize(pm_val = mean(pm_val, na.rm=TRUE)) %>% 
  mutate(
    pm_val_round = round(pm_val),
    aqi = factor(case_when(
      pm_val_round <= 50 ~ "Good",
      pm_val_round >= 51 & pm_val_round <= 100 ~ "Moderate",
      pm_val_round >= 101 & pm_val_round <= 150 ~ "Unhealthy for sensitive groups",
      pm_val_round >= 151 & pm_val_round <= 200 ~ "Unhealthy",
      pm_val_round >= 201 & pm_val_round <= 300 ~ "Very unhealthy",
      pm_val_round >= 301 ~ "Hazardous"
      ),
      levels = c("Good", "Moderate", "Unhealthy for sensitive groups", "Unhealthy", "Very unhealthy", "Hazardous")
    # ),
    # aqi_color = as.character(
    #   fct_recode(aqi, !!!(c(
    #     "green" = "Good",
    #     "yellow" = "Moderate",
    #     "orange" = "Unhealthy for sensitive groups",
    #     "red" = "Unhealthy",
    #     "purple" = "Very unhealthy",
    #     "maroon" = "Hazardous"
    #   )))
    )
  )

load("data/maps/pdx_map.RData")

# pdx_map %>% 
#   ggmap() +
#   facet_grid(
#     inout~range,
#     labeller = labeller(range = facet_range)
#   ) +
#   geom_point(
#     data = data_fire,
#     aes(x = long, y = lat, color = pm_val, size = pm_val),
#     inherit.aes = FALSE
#   ) +
#   scale_color_viridis(
#     option = "mako",
#     direction = -1,
#     end = 0.85
#   ) +
#   labs(
#     title = "Map of PM2.5 values in PDX",
#     color = "PM2.5 (µg/m^3): "
#   ) +
#   theme_void() +
#   theme(
#     legend.position = "top",
#     plot.background = element_rect(fill = "darkgray")
#   )

my_breaks <- seq(0, 350, by = 50)
lab_PM <- expression(paste("Average reported PM"[2.5]*" (", mu, "g/m"^3*") values in Portland in September 2020"))

pdx_map %>% 
  ggmap() +
  facet_wrap(
    ~range,
    labeller = labeller(range = facet_range)
  ) +
  geom_point(
    data = data_fire,
    color = "black",
    alpha = 0.8,
    aes(x = long, y = lat, shape = inout,
        #color = aqi,
        fill = pm_val, size = pm_val),
    inherit.aes = FALSE
  ) +
  scale_shape_manual(
    values = c(
      "outside" = 21,
      "inside" = 23
    )
  ) +
  scale_fill_viridis(
    # option = "mako",
    option = "viridis",
    direction = -1,
    end = 0.85,
    breaks = my_breaks
  ) +
  scale_size_continuous(breaks = my_breaks) +
  #scale_color_manual(values = c("#00e400", "#ffff00", "#ff7e00", "#ff0000", "#8f3f97", "#7e0023")) +
  guides(
    # fill = guide_legend(),
    size = FALSE,
    fill = guide_colorbar(barwidth=10)
  ) +
  theme_void() + 
  theme(
    legend.position = "top",
    legend.box = "vertical",
    plot.background = element_rect(fill = "darkgray")
  ) +
  labs(
    title = lab_PM,
    subtitle = "Data from PurpleAir",
    fill = "PM2.5 (µg/m^3): ",
    size = "PM2.5 (µg/m^3): ",
    #color = "AQI category: ",
    shape = "Sensor location: ",
    caption = "Outdoor sensor data from PA's ATM reported results, and indoor from CF1."
  )
```


```{r epa_wrangle}
data_corr <- data_day %>% 
  filter(inout == "outside") %>% 
  rename(
    cf1 = `PM2.5_CF1_ug.m3`,
    #atm = `PM2.5_ATM_ug.m3`,
    temp = `Temperature_F`,
    rh = `Humidity_.`
  ) %>% 
  filter(!(cf1 >= 1000)) %>% #filtering out max range
  select(c(loc_tag, ab, long, lat, date, cf1, temp, rh)) %>% 
  pivot_wider(names_from = ab, values_from = cf1) %>% 
  mutate(
    diff = (A-B),
    per_diff = 100*(abs(A-B))/((A+B)/2),
    drop = case_when(
      abs(diff) >= 5 & abs(per_diff) >= 62 ~ TRUE,
      TRUE ~ FALSE #fills all others with false
    )
  ) %>% 
  filter(drop != TRUE) %>% 
  select(!c(drop, diff, per_diff)) %>% 
  pivot_longer(cols = c("A", "B"), names_to = "ab") %>%
  group_by(loc_tag, long, lat, date) %>% 
  summarize(cf1 = mean(value, na.rm = TRUE),
            temp = mean(temp, na.rm = TRUE),
            rh = mean(rh, na.rm = TRUE)) %>% 
  ungroup() %>% 
  mutate(
    "epa_2020" = 0.524*cf1 - 0.0852*rh + 5.72,
    "epa_2021" = case_when(
      cf1 <= 343 ~ 0.52*cf1 - 0.086*rh + 5.75,
      cf1 > 343 ~ 0.46*cf1 + (3.93*10^(-4))*(cf1^2) +2.97
    )
  ) %>% 
  mutate(
    range = case_when(
      date >= date_pre_start & date <= date_pre_end ~ "pre",
      date >= date_fire_start & date <= date_fire_end ~ "fire",
      date >= date_post_start & date <= date_post_end ~ "post"
    ),
    range = factor(range, levels = c("pre", "fire", "post"))
  ) %>% 
  drop_na(range) %>% 
  group_by(loc_tag, long, lat, range)
```

```{r function_attempts, eval=FALSE}
# data_cf1 <- data_corr %>% 
#   summarize(mean = mean(cf1))
# 
# data_epa20 <- data_corr %>% 
#   summarize(mean = mean(epa_2020))
# 
# data_epa21 <- data_range %>% 
#   summarize(mean = mean(epa_2021))
# 
# pdx_map %>% 
#   ggmap() +
#   geom_point(
#     data = data_corr,
#     aes(x = long, y = lat, color = cf1),
#     inherit.aes = FALSE
#   )

map_aq <- function(pm25_input, range_input) {
  data_filtered <- data_corr %>% 
    filter(range == {{range_input}}) %>% 
    summarize(mean = mean({{pm25_input}})) %>% 
    ungroup()
  return(data_filtered)
  
  pdx_map %>% 
    ggmap() +
    geom_point(
      data = data_filtered,
      aes(x = long, y = lat, color = mean),
      inherit.aes = FALSE
    ) +
    scale_color_viridis()
}

map_aq(cf1, "pre")

pdx_map %>% 
  ggmap() +
  facet_wrap(~range) +
  geom_point(
    data = data_corr,
    aes(x = long, y = lat, color = cf1),
    inherit.aes = FALSE
  ) +
  scale_color_viridis() +
  theme(legend.position = "bottom")
```

```{r epa_corr_viz}
load("data/maps/pdx_map.RData")

data_corr_long <- data_corr %>% 
  pivot_longer(cols = c(cf1, epa_2020, epa_2021), names_to = "corr_factor", values_to = "pm_val") %>% 
  group_by(loc_tag, long, lat, range, corr_factor) %>% 
  summarise_at(c("temp", "rh", "pm_val"), mean, na.rm = TRUE)

#map_wildfire_epa <- pdx_map %>% 
pdx_map %>% 
  ggmap() +
  facet_grid(corr_factor~range) +
  geom_point(
    data = data_corr_long,
    aes(x = long, y = lat, color = pm_val),
    inherit.aes = FALSE
  ) +
  scale_color_viridis() +
  labs(
    title = "Map of PM2.5 values in PDX",
    subtitle = "Columns corrolate to time ranges.\nRows represent correction factors.",
    color = "PM2.5 (µg/m^3): "
  ) +
  theme_void() +
  theme(
    legend.position = "top",
    plot.background = element_rect(fill = "darkgray")
  )

#having trouble w ggsave right now.. will do manually
#ggsave(map_wildfire_epa, device = "png", path = "figures/map_wildfire_epa.png")
```


