---
title: "pa_mass_wrangle_alt"
author: "Gillian McGinnis"
date: "1/14/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)

#library(data.table)
```

```{r csv import}
my_file_paths <- list.files(path="data/raw",pattern="Primary Real Time",full.names=TRUE)

files_a <- my_file_paths[1:50]
files_b <- my_file_paths[51:100]
files_c <- my_file_paths[101:150]
files_d <- my_file_paths[151:200]
files_e <- my_file_paths[201:256]

raw_a <- files_a %>%
  set_names() %>%
  map_dfr(~read_csv(.x, col_types = cols(source = col_character(),
                                         created_at = col_character(),
                                         #`PM2.5_ATM_ug/m3` = col_double(),
                                         entry_id = col_skip(),
                                         UptimeMinutes = col_skip(),
                                         X11 = col_skip(),
                                         .default = col_double())), .id="source") %>%
                                         #.default = col_skip())), .id="source") %>%
  mutate(source = str_replace(source, ".\\w+\\/\\w+\\/", "")) #removes filepath name


raw_b <- files_b %>%
  set_names() %>%
  map_dfr(~read_csv(.x, col_types = cols(source = col_character(),
                                         created_at = col_character(),
                                         entry_id = col_skip(),
                                         UptimeMinutes = col_skip(),
                                         X11 = col_skip(),
                                         .default = col_double())), .id="source") %>%
  mutate(source = str_replace(source, ".\\w+\\/\\w+\\/", ""))


raw_c <- files_c %>%
  set_names() %>%
  map_dfr(~read_csv(.x, col_types = cols(source = col_character(),
                                         created_at = col_character(),
                                         entry_id = col_skip(),
                                         UptimeMinutes = col_skip(),
                                         X11 = col_skip(),
                                         .default = col_double())), .id="source") %>%
  mutate(source = str_replace(source, ".\\w+\\/\\w+\\/", ""))

raw_d <- files_d %>%
  set_names() %>%
  map_dfr(~read_csv(.x, col_types = cols(source = col_character(),
                                         created_at = col_character(),
                                         entry_id = col_skip(),
                                         UptimeMinutes = col_skip(),
                                         X11 = col_skip(),
                                         .default = col_double())), .id="source") %>%
  mutate(source = str_replace(source, ".\\w+\\/\\w+\\/", ""))

raw_e <- files_e %>%
  set_names() %>%
  map_dfr(~read_csv(.x, col_types = cols(source = col_character(),
                                         created_at = col_character(),
                                         entry_id = col_skip(),
                                         UptimeMinutes = col_skip(),
                                         X11 = col_skip(),
                                         .default = col_double())), .id="source") %>%
  mutate(source = str_replace(source, ".\\w+\\/\\w+\\/", ""))
```

```{r function, eval=FALSE}

set_test <- NULL

reading <- function(fileset){
  set_test <<- fileset %>%
    set_names() %>%
    map_dfr(~read_csv(.x, col_types = cols(source = col_character(),
                                         created_at = col_character(),
                                         entry_id = col_skip(),
                                         UptimeMinutes = col_skip(),
                                         X11 = col_skip(),
                                         .default = col_double())), .id="source") %>%
    mutate(source = str_replace(source, ".\\w+\\/\\w+\\/", "")) %>% #removes filepath name
    rbind(set_test)
  
  #return(set_test)
}

# files_mini <- my_file_paths[1:2]
# files_mini_2 <- my_file_paths[5:7]
# 
# reading(files_mini)
# reading(files_mini_2)

```


```{r megre}

data <- raw_a %>%
  full_join(raw_b) %>%
  full_join(raw_c) %>%
  full_join(raw_d) %>%
  full_join(raw_e)

```


```{r processing}
wrangled_data <- data %>%
  mutate(created_at = as_datetime(created_at), #converting from character to date time format; tz is in UTC
         date = date(created_at), #picking out just the date
         #time = strftime(created_at, format="%H:%M:%S"), # old way of picking time; outputs char
         #time_est = time, %>% #currently working on rounding out the seconds but for now it stands as is
         time = hms::as_hms(created_at)) %>% #picking out just the time
  mutate(coords = str_extract(source, "([0-9])\\w+\\.([0-9])\\w+\\s\\-([0-9])\\w+\\.([0-9])\\w+"), #grabbing coord data
         lat = str_extract(coords, "\\d+\\.\\d+\\s"), #latitude (north)
         lat = str_trim(lat, side = "right"), #removing extra whitespace
         lat = as.numeric(lat), #converting to numeric from character
         long = str_extract(coords, "\\-\\d+\\.\\d+"), #longitude (negative here, so west)
         long = as.numeric(long)) %>% #converting to numeric from character
  mutate(loc_tag = str_extract(source, "^[^\\(]+"), #grabbing location tag
         loc_tag = str_replace(loc_tag, " B ", ""),
         loc_tag = str_trim(loc_tag, side="right"), #removing extra whitespace
         ab = str_extract(source, " B \\("),
         ab = str_extract(ab, "B"),
         ab = replace_na(ab, "A")) %>%
  mutate(month = month(created_at, label=TRUE),
         day = day(created_at),
         hour = hour(created_at),
         min = minute(created_at)) %>%
  mutate(inout = str_extract(source, "(outside|inside)")) %>%
  group_by(loc_tag) %>%
  #select(loc_tag_new, inout, ab) %>%
  fill(inout) %>%
  select(!c(coords, source)) %>%
  select(c(loc_tag, created_at, inout, ab, long, lat, date, time, month, day, hour, min, everything()))

```

```{r environ clean}
remove(raw_a, raw_b, raw_c, raw_d, raw_e, files_a, files_b, files_c, files_d, files_e, data)
```

```{r loc data}
loc_data <- wrangled_data %>%
  select(loc_tag, inout, long, lat) %>%
  distinct(loc_tag, .keep_all = TRUE)
```


```{r summaries}
var_names <- names(wrangled_data)[13:22]
#var_keep <- names(wrangled_data)[3:7]

wrangled_daily <- wrangled_data %>%
  group_by(loc_tag, inout, ab, long, lat, date) %>%
  summarize_at(all_of(var_names), mean)

wrangled_hourly <- wrangled_data %>%
  group_by(loc_tag, inout, ab, long, lat, date, hour) %>%
  summarize_at(all_of(var_names), mean)

# wrangled_minute <- wrangled_data %>%
#   group_by(loc_tag, inout, ab, long, lat, date, hour, min) %>%
#   summarize_at(all_of(var_names), mean)
```



```{r saving data}
#write.csv(wrangled_data, "data/wrangled_new/wrangled_data.csv", row.names=TRUE)

write.csv(loc_data, "data/wrangled_new/loc_data.csv", row.names=TRUE)

write.csv(wrangled_daily, "data/wrangled_new/wrangled_day.csv", row.names=TRUE)
write.csv(wrangled_hourly, "data/wrangled_new/wrangled_hour.csv", row.names=TRUE)
#write.csv(wrangled_minute, "data/wrangled_new/wrangled_min.csv", row.names=TRUE)
```



```{r ab comp new, eval = FALSE}
var_names <- names(wrangled_data)[13:22]
a_vars <- paste(names(wrangled_data)[13:22],"_A",sep="")
b_vars <- paste(names(wrangled_data)[13:22],"_B",sep="")

wrangled_mini <- wrangled_data %>%
  filter(str_detect(loc_tag, "SE "))

ab_comp_new <- wrangled_mini %>%
  group_by(loc_tag, inout, ab, date, hour, min) %>%
  summarise_at(all_of(var_names), mean) %>%
  pivot_wider(names_from=ab, values_from=all_of(var_names)) %>%
  #group_by(loc_tag, inout, date, hour, min) %>%
  mutate(
    `PM1.0_CF1_ug/m3` = ((`PM1.0_CF1_ug/m3_A`-`PM1.0_CF1_ug/m3_B`)/`PM1.0_CF1_ug/m3_A`)*100,
    `PM2.5_CF1_ug/m3` = ((`PM2.5_CF1_ug/m3_A`-`PM2.5_CF1_ug/m3_B`)/`PM2.5_CF1_ug/m3_A`)*100,
    `PM10.0_CF1_ug/m3` = ((`PM10.0_CF1_ug/m3_A`-`PM2.5_CF1_ug/m3_B`)/`PM2.5_CF1_ug/m3_A`)*100,
    `RSSI_dbm` = ((`RSSI_dbm_A`-`RSSI_dbm_B`)/`RSSI_dbm_A`)*100,
    `Temperature_F` = ((`Temperature_F_A` - `Temperature_F_B`)/`Temperature_F_A`)*100,
    `Humidity_%` = ((`Humidity_%_A` - `Humidity_%_B`)/`Humidity_%_A`)*100,
    `PM2.5_ATM_ug/m3` = ((`PM2.5_ATM_ug/m3_A`-`PM2.5_ATM_ug/m3_B`)/`PM2.5_ATM_ug/m3_A`)*100,
    `ADC` = ((`ADC_A` - `ADC_B`)/`ADC_A`)*100,
    `Pressure_hpa` = ((`Pressure_hpa_A` - `Pressure_hpa_B`)/`Pressure_hpa_A`)*100,
    `IAQ` = ((`IAQ_A` - `IAQ_B`)/`IAQ_A`)*100
  ) %>%
  select(loc_tag, inout, date, hour, min, all_of(var_names)) %>%
  group_by(loc_tag, inout) %>%
  summarize_at(all_of(var_names), mean)
```