---
title: "pa_wrangle_mass"
author: "Gillian McGinnis"
date: "1/11/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse) #dplyr, ggplot2, etc
library(lubridate) #better time/date manipulation
library(viridis) #better color scales
library(ggthemes) #better themes
#library(janitor) #used for clean_names function
```


```{r data}
#my_file_paths <- list.files(path = "data/raw", pattern = ".+\\(*(outside*)\\w+\\)", full.names = TRUE)

#my_file_paths <- list.files(path="data/raw", pattern=".+(E )",full.names=TRUE) #smaller subset
my_file_paths <- list.files(path="data/raw", pattern="SE",full.names=TRUE) #smaller subset

# raw_data <- my_file_paths %>%
#   set_names() %>%
#   map_dfr(read_csv, .id = "source") %>%
#   mutate(source = str_replace(source, ".\\w+\\/\\w+\\/", "")) #removes filepath name

# raw_data <- my_file_paths %>%
#   set_names() %>%
#   #map_dfr(~read_csv(.x, col_types = cols(.default = "c")), .id="source") %>%
#   map_dfr(~read_csv(.x, col_types = cols(entry_id = col_double(),
#                                          `>=0.3um/dl` = col_double(),
#                                          `>=0.5um/dl` = col_double(),
#                                          `>1.0um/dl` = col_double(),
#                                          `>=2.5um/dl` = col_double(),
#                                          `>=5.0um/dl` = col_double(),
#                                          `>=10.0um/dl` = col_double(),
#                                          `PM1.0_ATM_ug/m3` = col_double())), .id="source") %>%
#   mutate(source = str_replace(source, ".\\w+\\/\\w+\\/", "")) #removes filepath name

raw_data <- my_file_paths %>%
  set_names() %>%
  map_dfr(~read_csv(.x, col_types = cols(source = col_character(),
                                         created_at = col_character(),
                                         .default = col_double())), .id="source") %>%
  mutate(source = str_replace(source, ".\\w+\\/\\w+\\/", "")) #removes filepath name
```


```{r tidying}

df <- raw_data %>%
  drop_na(`PM2.5_CF1_ug/m3`) %>% #removes empty values for stat of interest
  mutate(created_at = as_datetime(created_at), #converting from character to date time format; tz is in UTC
         date = date(created_at), #picking out just the date
         #time = strftime(created_at, format="%H:%M:%S"), # old way of picking time; outputs char
         time = hms::as_hms(created_at), #picking out just the time
         time_est = time) %>% #currently working on rounding out the seconds but for now it stands as is
  mutate(coords = str_extract(source, "([0-9])\\w+\\.([0-9])\\w+\\s\\-([0-9])\\w+\\.([0-9])\\w+"), #grabbing coord data
         lat = str_extract(coords, "\\d+\\.\\d+\\s"), #latitude (north)
         lat = str_trim(lat, side = "right"), #removing extra whitespace
         lat = as.numeric(lat), #converting to numeric from character
         long = str_extract(coords, "\\-\\d+\\.\\d+"), #longitude (negative here, so west)
         long = as.numeric(long), #converting to numeric from character
         loc_tag = str_extract(source, "^[^\\(]+"), #grabbing location tag
         loc_tag = str_trim(loc_tag, side = "right")) %>% #removing extra whitespace
  mutate(hour = hour(created_at),
         hour_round = hour(round_date(created_at, unit="hour")),
         year = year(created_at),
         month = month(created_at, label=TRUE),
         day = day(created_at))


unique_locations <- unique(df$loc_tag) #creates list of unique locations for quick reference
unique_vars <- names(df) #creates list of columns for quick reference
```


```{r hourly heatmap}
# Source: https://www.r-graph-gallery.com/283-the-hourly-heatmap.html

ggplot(df, aes(day, hour, fill = `PM2.5_CF1_ug/m3`))+
  #geom_tile(color = "white", size=0.1)+
  geom_tile()+
  scale_fill_viridis(name = "Hrly PM25", option = "plasma")+
  facet_grid(loc_tag~month)+
  scale_y_continuous(trans = "reverse", breaks = unique(df$hour))+
  scale_x_continuous(breaks = c(1,10,20,31))+
  theme_minimal(base_size=8)+
  labs(title = paste("Hourly PM25"), x= "Day", y = "Hour commencing")+
  theme(legend.position="bottom",
        plot.title=element_text(size=14, hjust = 0),
        axis.text.y=element_text(size=6),
        strip.background = element_rect(colour="white"),
        axis.ticks=element_blank(),
        axis.text=element_text(size=7),
        legend.title=element_text(size=8),
        legend.text=element_text(size=6),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank())

#flip flop
ggplot(data=subset(df, month%in%c("Sep","Oct","Nov")), aes(hour, day, fill = `PM2.5_CF1_ug/m3`))+
  #geom_tile(color = "white", size=0.1)+
  geom_tile()+
  scale_fill_viridis(name = "Hrly PM25", option = "plasma")+
  facet_grid(month~loc_tag)+
  scale_x_continuous(trans = "reverse", breaks = unique(df$hour))+
  scale_y_continuous(breaks = c(1,10,20,31))+
  theme_minimal(base_size=8)+
  labs(title = paste("Hourly PM25"), y= "Day", x = "Hour commencing")+
  theme(legend.position="bottom",
        plot.title=element_text(size=14, hjust = 0),
        axis.text.x=element_text(size=6),
        strip.background = element_rect(colour="white"),
        axis.ticks=element_blank(),
        axis.text=element_text(size=7),
        legend.title=element_text(size=8),
        legend.text=element_text(size=6),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank())
```


```{r summary stats}
summary_df <- df %>%
  group_by(loc_tag, date, hour) %>%
  summarize(mean = mean(`PM2.5_CF1_ug/m3`),
            sd = sd(`PM2.5_CF1_ug/m3`)) %>%
  mutate(month = month(date, label=TRUE),
         day = day(date))

# ggplot(summary_df, aes(x = hour, y = mean, color = loc_tag))+
#   facet_grid(day~month)+
#   geom_path()

ggplot(summary_df, aes(x = date, y = mean, color=loc_tag))+
  geom_line(alpha=0.1)+
  geom_point(size=0.2, shape=3, alpha=0.5)+
  theme_minimal(base_size=8)+
  theme(legend.position="bottom",
        plot.title=element_text(size=14, hjust = 0),
        axis.text.y=element_text(size=6),
        strip.background = element_rect(colour="white"),
        axis.ticks=element_blank(),
        axis.text=element_text(size=7),
        legend.title=element_text(size=8),
        legend.text=element_text(size=6))
```

```{r daily heatmap}
summary_daily <- summary_df %>%
  group_by(loc_tag, date) %>%
  rename(mean_orig = mean,
         sd_orig = sd) %>%
  summarize(mean = mean(mean_orig),
            sd = sd(mean_orig)) %>%
  mutate(month = month(date, label=TRUE),
         day = day(date))

ggplot(data=subset(summary_daily, month%in%c("Oct","Nov")), aes(x=day, y=0, fill=mean))+
#ggplot(summary_daily, aes(x=day, y=0, fill=mean))+
  geom_tile()+
  scale_fill_viridis(name = "Daily PM25", option = "plasma")+
  facet_grid(loc_tag~month)+
  scale_x_continuous(breaks = c(1,10,20,31))+
  theme_minimal(base_size=8)+
  labs(title = paste("Daily PM25"), x= "Day", y="")+
  theme(legend.position="bottom",
        plot.title=element_text(size=14, hjust = 0),
        #axis.text.y=element_text(size=6),
        axis.text.y=element_blank(),
        strip.background = element_rect(colour="white"),
        axis.ticks=element_blank(),
        axis.text=element_text(size=7),
        legend.title=element_text(size=8),
        legend.text=element_text(size=6),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank())
```

