---
title: "pa_wrangle_mass_ab"
author: "Gillian McGinnis"
date: "1/13/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse) #dplyr, etc
library(lubridate) #better time/date manipulation
```

```{r ab grab}
#my_file_paths <- list.files(path="data/raw", pattern="SE",full.names=TRUE) #smaller subset
all_paths <- list.files(path="data/raw", pattern="Real Time",full.names=TRUE)

my_files <- all_paths %>%
  as.data.frame() %>%
  rename(source = ".") %>%
  mutate(source = str_replace(source, ".\\w+\\/\\w+\\/", "")) %>% #removes filepath name
  mutate(loc_tag = str_extract(source, "^[^\\(]+"),
         #loc_tag_new = str_replace(loc_tag, " B ", ""),
         #inoutun = str_extract(source, "(outside|inside|undefined)"),
         inout = str_extract(source, "(outside|inside)"),
         ab = str_extract(source, " B \\("),
         primsec = str_extract(source, "\\) (Primary|Secondary)")) %>%
  mutate(loc_tag = str_replace(loc_tag, " B ", ""),
         loc_tag = str_trim(loc_tag, side="right"),
         primsec = str_extract(primsec, "(Primary|Secondary)"),
         ab = str_extract(ab, "B"),
         ab = replace_na(ab, "A")) %>%
  group_by(loc_tag) %>%
  #select(loc_tag_new, inout, ab) %>%
  fill(inout) %>%
  filter(inout == "outside",
         primsec == "Primary") %>%
  select(!c(inout, primsec))
```

```{r pm25}
my_file_paths <- list.files(path = "data/raw", pattern = "STAR", full.names = TRUE)
#my_file_paths <- list.files(path = "data/raw", pattern = "Primary Real Time", full.names=TRUE)

raw_data <- my_file_paths %>%
  set_names()%>%
  map_df(~read_csv(.x, col_types = cols(#source = col_character(),
                                        created_at = col_character(),
                                        X11 = col_character(),
                                        .default = "d")), .id="source")

processed_data <- raw_data %>%
  select(!c("entry_id", "UptimeMinutes", "X11")) %>%
  select(source, created_at, `PM2.5_CF1_ug/m3`) %>%
  drop_na(`PM2.5_CF1_ug/m3`) %>%
  mutate(source = str_replace(source, ".\\w+\\/\\w+\\/", "")) %>% #removes filepath name
  mutate(loc_tag = str_extract(source, "^[^\\(]+"),
         #loc_tag_new = str_replace(loc_tag, " B ", ""),
         #inoutun = str_extract(source, "(outside|inside|undefined)"),
         inout = str_extract(source, "(outside|inside)"),
         ab = str_extract(source, " B \\("),
         primsec = str_extract(source, "\\) (Primary|Secondary)")) %>%
  mutate(loc_tag = str_replace(loc_tag, " B ", ""),
         loc_tag = str_trim(loc_tag, side="right"),
         primsec = str_extract(primsec, "(Primary|Secondary)"),
         ab = str_extract(ab, "B"),
         ab = replace_na(ab, "A")) %>%
  group_by(loc_tag) %>%
  #select(loc_tag_new, inout, ab) %>%
  fill(inout) %>%
  filter(inout == "outside",
         primsec == "Primary") %>%
  select(!c(inout, primsec)) %>%
  mutate(created_at = as_datetime(created_at), #converting from character to date time format; tz is in UTC
         date = date(created_at), #picking out just the date
         #time = strftime(created_at, format="%H:%M:%S"), # old way of picking time; outputs char
         time = hms::as_hms(created_at), #picking out just the time
         hour = hour(created_at),
         #hour_round = hour(round_date(created_at, unit="hour")),
         day = day(created_at),
         month = month(created_at, label = TRUE)) %>%
  mutate(coords = str_extract(source, "([0-9])\\w+\\.([0-9])\\w+\\s\\-([0-9])\\w+\\.([0-9])\\w+"), #grabbing coord data
         lat = str_extract(coords, "\\d+\\.\\d+\\s"), #latitude (north)
         lat = str_trim(lat, side = "right"), #removing extra whitespace
         lat = as.numeric(lat), #converting to numeric from character
         long = str_extract(coords, "\\-\\d+\\.\\d+"), #longitude (negative here, so west)
         long = as.numeric(long)) #converting to numeric from character
```

```{r data import}
#file_paths_all <- list.files(path = "data/raw", pattern = "Primary Real Time", full.names=TRUE)
file_paths_all <- list.files(path = "data/raw", pattern = "SE ", full.names=TRUE)
#file_paths_a <- list.files(path = "data/raw", pattern = "(outside|inside).+(Primary)", full.names=TRUE)
#file_paths_b <- list.files(path = "data/raw", pattern = "(undefined).+(Primary)", full.names=TRUE)

all_raw <- file_paths_all %>%
  set_names()%>%
  map_df(~read_csv(.x, col_types = cols(#source = col_character(),
                                        created_at = col_character(),
                                        X11 = col_character(),
                                        .default = "d")), .id="source")

all_raw <- all_raw %>%
  mutate(source = str_replace(source, ".\\w+\\/\\w+\\/", "")) #removes filepath name
```


```{r location reference table}
loc_data <- all_raw %>%
  distinct(source) %>%
  #mutate(source = str_replace(source, ".\\w+\\/\\w+\\/", "")) %>% #removes filepath name
  mutate(loc_tag = str_extract(source, "^[^\\(]+"),
         loc_tag = str_replace(loc_tag, " B ", ""),
         loc_tag = str_trim(loc_tag, side="right")) %>%
         #loc_tag_new = str_replace(loc_tag, " B ", ""),
         #inoutun = str_extract(source, "(outside|inside|undefined)"),
  mutate(inout = str_extract(source, "(outside|inside)")) %>%
  group_by(loc_tag) %>%
  #select(loc_tag_new, inout, ab) %>%
  fill(inout) %>%
  mutate(coords = str_extract(source, "([0-9])\\w+\\.([0-9])\\w+\\s\\-([0-9])\\w+\\.([0-9])\\w+"), #grabbing coord data
         lat = str_extract(coords, "\\d+\\.\\d+\\s"), #latitude (north)
         lat = str_trim(lat, side = "right"), #removing extra whitespace
         lat = as.numeric(lat), #converting to numeric from character
         long = str_extract(coords, "\\-\\d+\\.\\d+"), #longitude (negative here, so west)
         long = as.numeric(long)) %>%
  select(!c(source, coords)) %>%
  distinct(loc_tag, .keep_all=TRUE)
```

```{r ab check}
var_of_interest <- "PM2.5_ATM_ug/m3"

ab_comp <- all_raw %>%
  select(source, created_at, var_of_interest) %>%
  drop_na(var_of_interest) %>%
  mutate(loc_tag = str_extract(source, "^[^\\(]+"),
         loc_tag = str_replace(loc_tag, " B ", ""),
         loc_tag = str_trim(loc_tag, side="right"),
         ab = str_extract(source, " B \\("),
         ab = str_extract(ab, "B"),
         ab = replace_na(ab, "A")) %>%
  select(!c(source)) %>%
  mutate(created_at = as_datetime(created_at), #converting from character to date time format; tz is in UTC
         date = date(created_at), #picking out just the date
         time = hms::as_hms(created_at)) %>% #picking out just the time
    mutate(hour = hour(created_at),
           min = minute(created_at),
         #hour_round = hour(round_date(created_at, unit="hour")),
         month = month(created_at, label=TRUE),
         day = day(created_at)) %>%
  group_by(loc_tag, ab, date, hour, min) %>%
  summarize(mean = mean(`PM2.5_ATM_ug/m3`)) %>% #var_of_interest
  ungroup() %>%
  pivot_wider(names_from = ab, values_from=mean) %>%
  #per_change_a = ((A-B)/A)*100,
         #per_change_b = ((B-A)/B)*100,
  #mutate(per_change_abs = abs(((A-B)/A)*100)) %>%
  mutate(per_change = ((A-B)/A)*100) %>%
  #replace(per_change, is.infinite(x), NA) %>%
  #replace(per_change, is.infinite(per_change), NA) %>%
  #mutate(per_change = case_when(is.infinite(per_change)==TRUE ~ NA)) %>%
  #drop_na(per_change) %>%
  select(loc_tag, per_change) %>%
  #per_change_alt = case_when(per_change > 100) ~ NA,
  mutate(per_change_alt = case_when(per_change < 100 ~ per_change)) %>%
  mutate(per_change_alt = case_when(per_change > -100 ~ per_change)) %>%
  #mutate(per_change_alt = case_when((per_change > 100 | per_change < 0) ~ NA))
  drop_na(per_change_alt) %>%
  select(loc_tag, per_change) %>%
  group_by(loc_tag) %>%
  summarize(mean_per = mean(per_change)) %>%
  #mutate(mean_per = -15) %>%
  #reliable = case_when((mean_per > 10 | mean_per < -10) ~ FALSE),
  mutate(reliable = case_when((mean_per <= 15 & mean_per >= -15) ~ TRUE)) %>%
  drop_na(reliable) %>%
  select(!c(reliable))
```

```{r ab and loc check}
sensor_info <- loc_data %>%
  full_join(ab_comp)
```



