---
title: "sparklines"
author: "Gillian McGinnis"
date: "7/6/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(openair)

calendarPlot(
  data_daily, pollutant = "epa_2021", year = 2021,
  annotate = "value",
  cols = "Purples"
)

data_hourly %>% 
  rename(date = date_hour) %>% 
  timeVariation(pollutant = c("lrapa", "pm25_atm", "epa_2021"))


data_hourly %>% 
  rename(date = date_hour) %>% 
  timeVariation(pollutant = c("epa_2020", "epa_2021", "epa_atm"))

data_hourly %>% 
  # left_join(data_meta) %>% 
  # filter(label == "Lighthouse") %>% 
  apply_date_tags() %>% 
  rename(date = date_hour) %>% 
  timeVariation(pollutant = "epa_2021", group = "date_tag", cols = "Dark2")

data_deq %>% 
  apply_date_tags() %>% 
  rename(date=date_hour) %>% 
  timeVariation(pollutant = "pm25_deq", group = "date_tag", cols = "Dark2")

data_deq %>% 
  rename(
    "ws" = "wind_speed",
    "wd" = "wind_direction"
  ) %>% 
  polarPlot(
    pollutant = "pm25_deq",
    col = "Purples",
    key.position = "bottom"
  )


data_hourly %>% 
  filter(site_id == "6c18a7181a09037c_47107") %>% 
  select(site_id, date_hour, date_tag, hour_tag, epa_2021) %>% 
  full_join(data_deq %>% select(date_hour, pm25_deq, wind_speed, wind_direction)) %>% 
  rename(
    "ws" = "wind_speed",
    "wd" = "wind_direction"
  ) %>% 
  polarPlot(
    pollutant = "epa_2021",
    col = "Purples"
  )

data_deq %>% 
  rename(
    "ws" = "wind_speed",
    "wd" = "wind_direction"
  ) %>% 
  polarPlot(
    pollutant = "pm25_deq",
    col = "Purples"
  )

```

```{r}
data_hourly %>% 
  filter(site_id == "6c18a7181a09037c_47107") %>% 
  column_dt(c("date", "hour")) %>%
  mutate(hour = hour(date_hour)) %>% 
  mutate(
    tag = case_when(
      hour >= 0 & hour <= 11 ~ "AM",
      hour >= 12 & hour <= 23 ~ "PM"
    # ),
    # hour_new = case_when(
    #   tag == "PM" ~ hour-12,
    #   tag == "AM" ~ hour+0,
    #   hour == 0 ~ 12
    )
  ) %>% 
  apply_date_tags() %>% 
  ggplot(aes(x = hour, y = epa_2021, group = date, color = tag)) +
  #facet_grid(date_tag ~ tag) +
  facet_wrap(~date_tag) +
  #ggplot(aes(x = hour, y = pm25_deq, color = as.factor(date), group = as.factor(date))) +
  coord_polar() +
  geom_line()

data_hourly %>% 
  filter(site_id == "6c18a7181a09037c_47107") %>% 
  column_dt(c("date", "hour")) %>% 
  apply_date_tags() %>% 
  mutate(date = as.factor(date)) %>% 
  ggplot(aes(x = hour, y = epa_2021, group = date, color = date_tag)) +
  coord_polar() +
  geom_line()

data_hourly %>% 
  filter(site_id == "6c18a7181a09037c_47107") %>% 
  column_dt(c("date", "hour")) %>% 
  ggplot(aes(x = hour, y = epa_2021, group = date, color = date)) +
  geom_line() +
  geom_point()

data_deq %>% 
  column_dt(c("date", "hour")) %>% 
  #filter(date == "2021-07-01") %>% 
  mutate(hour = hour(date_hour)) %>% 
  ggplot(aes(x = humidity, y = pm25_deq, color = hour, group = date)) +
  geom_path() +
  geom_point()

data_deq %>% 
  column_dt(c("date", "hour")) %>% 
  ggplot(aes(x = hour, y = pm25_deq, color = date, group = date)) + 
  geom_line()

data_hourly %>% 
  filter(site_id == "6c18a7181a09037c_47107") %>% 
  select(site_id, date_hour, date_tag, hour_tag, epa_2021) %>% 
  full_join(data_deq %>% select(date_hour, pm25_deq)) %>% 
  drop_na() %>% 
  mutate(per_error = ((epa_2021-pm25_deq)/pm25_deq)*100) %>% 
  distinct() %>% 
  ggplot(aes(x = date_hour, y = per_error)) + 
  #facet_grid(site_id~.) +
  scale_x_datetime(breaks = "1 day") +
  # geom_hline(yintercept = 0) +
  # geom_line(color = "red") +
  # geom_point(aes(color = hour_tag))
  geom_area(aes(y = ifelse(per_error<0, per_error, 0)), fill = "red") +
  geom_area(aes(y = ifelse(per_error>0, per_error, 0)), fill = "green") +
  geom_hline(yintercept = 0)

data_hourly %>% 
  select(site_id, date_hour, date_tag, hour_tag, epa_2021) %>% 
  full_join(data_deq %>% select(date_hour, pm25_deq)) %>% 
  drop_na() %>% 
  mutate(per_error = ((epa_2021-pm25_deq)/pm25_deq)*100) %>% 
  ggplot(aes(x = date_hour, y = per_error, group = site_id)) + 
  scale_x_datetime(breaks = "1 day") +
  geom_hline(yintercept = 0) +
  geom_line() +
  geom_point()


data_hourly %>% 
  drop_na() %>% 
  left_join(data_meta) %>% 
  ggplot(aes(x = date_hour, y = epa_2021, group = site_id)) +
  facet_wrap(~label) +
  geom_point(data = (data_hourly %>% drop_na()), color = "gray") +
  geom_point(color = "red")

data_hourly %>% 
  drop_na() %>% 
  left_join(data_meta) %>% 
  ggplot(aes(x = date_hour, y = epa_2021, group = site_id)) +
  facet_grid(label~date_tag, scales = "free_x") +
  #facet_wrap(~label, drop = FALSE) +
  geom_line(data = (data_hourly %>% drop_na()), color = "gray") +
  geom_line(color = "red") +
  ggthemes::theme_few()

data_hourly %>% 
  drop_na() %>% 
  left_join(data_meta) %>% 
  filter(str_detect(label, "SE \\D")) %>%
  ggplot(aes(x = date_hour, y = epa_2021, group = site_id)) +
  #facet_grid(label~date_tag, scales = "free_x") +
  facet_grid(label~.) +
  # facet_wrap(~label) +
  geom_line(data = (data_hourly %>% drop_na()), color = "gray") +
  geom_line(data = (data_deq %>% drop_na(pm25_deq) %>% rename(epa_2021 = pm25_deq)), color = "green") +
  geom_line(color = "red") +
  theme_minimal() +
  scale_x_datetime(breaks = "1 day", date_labels = "%d %b") +
  theme(axis.text.x = element_text(angle = 30, hjust = 1), axis.ticks.x = element_line())



hourly_min <- data_hourly %>% 
  drop_na(epa_2021) %>% 
  left_join(data_meta) %>% 
  group_by(site_id) %>% 
  filter(epa_2021==min(epa_2021)) %>%
  distinct() %>% 
  select(site_id, label, date_hour, epa_2021) %>% 
  mutate(epa_2021_text = as.character(sprintf(paste0("%.", "2", "f"), round(epa_2021, digits = 2))))

hourly_max <- data_hourly %>% 
  drop_na(epa_2021) %>% 
  left_join(data_meta) %>% 
  group_by(label) %>% 
  filter(epa_2021==max(epa_2021)) %>%
  distinct() %>% 
  select(site_id, label, date_hour, epa_2021) %>% 
  mutate(epa_2021_text = as.character(sprintf(paste0("%.", "2", "f"), round(epa_2021, digits = 2))))

data_hourly %>% 
  drop_na(epa_2021) %>% 
  left_join(data_meta) %>% 
  filter(str_detect(label, "SE \\D")) %>%
  ggplot(aes(x = date_hour, y = epa_2021)) +
  facet_grid(label~.) +
  geom_line(data = (data_hourly %>% drop_na()), color = "gray", aes(group = site_id)) +
  geom_line(data = (data_hourly %>% ungroup() %>% group_by(date_hour) %>% summarize(epa_2021=mean(epa_2021,na.rm=TRUE))), color = "green") +
  geom_line(color = "black", aes(group = site_id)) +
  geom_point(color = "black", size = 0.5) +
  geom_point(
    data = (hourly_max %>% filter(str_detect(label, "SE \\D"))),
    color = "red",
    shape = 1,
    size = 1.5
  ) +
  ggrepel::geom_text_repel(
    data = (hourly_max %>% filter(str_detect(label, "SE \\D"))),
    color = "red",
    aes(label = epa_2021_text)
  ) +
  geom_point(
    data = (hourly_min %>% filter(str_detect(label, "SE \\D"))),
    color = "blue",
    shape = 1,
    size = 1.5
  ) +
  ggrepel::geom_text_repel(
    data = (hourly_min %>% filter(str_detect(label, "SE \\D"))),
    color = "blue",
    aes(label = epa_2021_text)
  ) +
  theme_minimal() +
  scale_x_datetime(breaks = "1 day", date_labels = "%d %b") +
  theme(axis.text.x = element_text(angle = 30, hjust = 1), axis.ticks.x = element_line())

extrema <- data_hourly %>% 
  drop_na(epa_2021) %>% 
  left_join(data_meta) %>% 
  filter(str_detect(label, "SE \\D")) %>%
  select(site_id, label, date_hour, epa_2021) %>% 
  group_by(site_id) %>% 
  mutate(
    max = case_when(epa_2021 == max(epa_2021, na.rm=TRUE) ~ epa_2021),
    min = case_when(epa_2021 == min(epa_2021, na.rm=TRUE) ~ epa_2021),
    max = as.character(sprintf(paste0("%.", "2", "f"), round(max, digits = 2))),
    min = as.character(sprintf(paste0("%.", "2", "f"), round(min, digits = 2))),
    max = na_if(max, "NA"),
    min = na_if(min, "NA")
  )

library(ggrepel)

# extrma_avgs 
extrema_avg <- data_hourly %>% 
  # drop_na(epa_2021) %>% 
  # left_join(data_meta) %>% 
  # filter(str_detect(label, "SE \\D")) %>%
  select(date_hour, epa_2021) %>% 
  group_by(date_hour) %>% 
  summarize(epa_2021 = mean(epa_2021, na.rm = TRUE)) %>% 
  mutate(
    max = case_when(epa_2021 == max(epa_2021, na.rm=TRUE) ~ epa_2021),
    min = case_when(epa_2021 == min(epa_2021, na.rm=TRUE) ~ epa_2021),
    max = as.character(sprintf(paste0("%.", "2", "f"), round(max, digits = 2))),
    min = as.character(sprintf(paste0("%.", "2", "f"), round(min, digits = 2))),
    max = na_if(max, "NA"),
    min = na_if(min, "NA")
  ) %>% 
  # mutate(
  #   label = NA,
  #   site_id = NA
  # )
  mutate(
    label = "Average",
    site_id = "Averages"
  )

label_order <- data_meta %>% 
  select(site_id,label,latitude) %>% 
  rbind(data.frame(
    label = "Average",
    site_id = "Averages",
    latitude = min(data_meta$latitude) - 1
  )) %>% 
  mutate(label = fct_reorder(as.factor(label), desc(latitude))) %>% 
  pull(label)

label_order <- data_meta %>% 
  select(site_id, label, latitude) %>% 
  mutate(label = fct_reorder(as.factor(label), desc(latitude))) %>% 
  pull(label)

orderr <- fct_inorder(c(levels(label_order), "Average"))

data_hourly %>% 
  drop_na(epa_2021) %>% 
  select(date_hour) %>% 
  crossing((data_hourly %>% distinct(site_id) %>% rbind("Averages"))) %>% 
  left_join(rbind(extrema, extrema_avg)) %>%
  mutate(label = factor(label, orderr)) %>% 
  drop_na(epa_2021) %>% 
  ggplot(aes(x = date_hour, y = epa_2021)) +
  facet_grid(label~., drop=TRUE) +
  geom_line(
    data = data_hourly %>% drop_na(epa_2021),
    color = "gray",
    aes(group = site_id)
  ) +
  geom_line(color = "black", data = . %>% filter(site_id!="Averages")) +
  geom_line(color = "green", data = . %>% filter(site_id=="Averages"))

# Works!!
data_hourly %>% 
  drop_na(epa_2021) %>% 
  select(date_hour) %>% 
  crossing((data_hourly %>% distinct(site_id) %>% rbind("Averages"))) %>% 
  left_join(rbind(extrema, extrema_avg)) %>%
  mutate(label = factor(label, orderr)) %>% 
  drop_na(epa_2021) %>% 
  ggplot(aes(x = date_hour, y = epa_2021)) +
  facet_grid(label~.) +
  # facet_wrap(~label) +
  geom_line(
    data = data_hourly %>% drop_na(epa_2021),
    color = "gray",
    alpha = 0.5,
    aes(group = site_id)
  ) +
  geom_line(
    color = "black",
    data = . %>% filter(site_id!="Averages")
  ) +
  geom_line(
    color = "darkgreen",
    data = . %>% filter(site_id=="Averages")
  ) +
  geom_point(
    data = . %>% filter(!is.na(max)),
    color = "darkorange",
    shape = 1
  ) +
  geom_point(
    data = . %>% filter(!is.na(min)),
    color = "royalblue",
    shape = 1
  ) +
  geom_text_repel(
    data = . %>% mutate(max = replace_na(max, "")),
    min.segment.length = 0,
    box.padding = 0.5,
    max.overlaps = Inf,
    color = "darkorange",
    aes(label = max)
  ) +
  geom_text_repel(
    data = . %>% mutate(min = replace_na(min, "")),
    min.segment.length = 0,
    box.padding = 0.5,
    max.overlaps = Inf,
    color = "royalblue",
    aes(label = min)
  ) +
  theme_minimal() +
  scale_x_datetime(breaks = "1 day", date_labels = "%d %b") +
  theme(axis.text.x = element_text(angle = 30, hjust = 1), axis.ticks.x = element_line()) +
  labs(
    x = "Time",
    y = "EPA-corrected PM2.5",
    title = "PM2.5 values over time",
    subtitle = "Maximum and minimum values by monitor are marked by orange and blue text, respectively.",
    caption = "Black lines indicate the monitor of interest (labelled on the right).
    Gray lines represent individual monitor time series.
    The green line at the bottom represents the average by hour."
  )


data_hourly %>% 
  drop_na(epa_2021) %>% 
  left_join(data_meta) %>% 
  # filter(str_detect(label, "SE \\D")) %>%
  select(site_id, label, date_hour, epa_2021) %>% 
  group_by(site_id) %>% 
  mutate(
    max = case_when(epa_2021 == max(epa_2021, na.rm=TRUE) ~ epa_2021),
    min = case_when(epa_2021 == min(epa_2021, na.rm=TRUE) ~ epa_2021),
    max = as.character(sprintf(paste0("%.", "2", "f"), round(max, digits = 2))),
    min = as.character(sprintf(paste0("%.", "2", "f"), round(min, digits = 2))),
    max = na_if(max, "NA"),
    min = na_if(min, "NA")
  ) %>% 
  distinct() %>% 
  ggplot(aes(x = date_hour, y = epa_2021)) +
  facet_wrap(~label) +
  # facet_grid(label~.) +
  geom_line(
    data = data_hourly %>% drop_na(epa_2021),
    color = "gray",
    aes(group = site_id)
  ) +
  # geom_line(
  #   data = . %>% select(!label),
  #   color = "gray",
  #   aes(group = site_id)
  # ) +
  # # AVERAGE LINES
  # geom_hline(
  #   color = "black",
  #   linetype = "dashed",
  #   alpha = 0.5,
  #   data = . %>% 
  #     group_by(label) %>% 
  #     summarize(mean = mean(epa_2021,na.rm=TRUE)),
  #   aes(yintercept = mean)
  # ) +
  # geom_hline(
  #   color = "green",
  #   linetype = "dashed",
  #   alpha = 0.5,
  #   data = . %>% 
  #     ungroup() %>% 
  #     summarize(mean = mean(epa_2021, na.rm=TRUE)),
  #   aes(yintercept = mean)
  # ) +
  # # END OF AVG LINES
  geom_line(
    color = "green",
    data = . %>%
      ungroup() %>%
      group_by(date_hour) %>%
      summarize(epa_2021 = mean(epa_2021, na.rm=TRUE))
  ) +
  geom_line(color = "black") + 
  # geom_point(
  #   # data = data_hourly %>% drop_na(epa_2021),
  #   data = . %>% filter(is.na(max), is.na(min)),
  #   color = "black",
  #   size = 1,
  #   aes(group = site_id)
  # ) + 
  # geom_point(
  #   data = . %>% filter(is.na(max), is.na(min)) %>% select(!label),
  #   color = "transparent"
  # ) +
  geom_point(
    data = . %>% filter(!is.na(max)),
    color = "red"
  ) +
  geom_point(
    data = . %>% filter(!is.na(min)),
    color = "blue"
  ) +
  geom_text_repel(
    # data = . %>% filter(!is.na(max)),
    data = . %>% arrange(desc(max)) %>% mutate(max = replace_na(max, "")),
    color = "red",
    min.segment.length = 0,
    box.padding = 0.5,
    aes(label = max)
  ) +
  geom_text_repel(
    # data = . %>% filter(!is.na(min)),
    data = . %>% arrange(desc(min)) %>% mutate(min = replace_na(min, "")),
    max.overlaps = Inf,
    color = "blue",
    min.segment.length = 0,
    box.padding = 0.5,
    aes(label = min)
  ) +
  theme_minimal() +
  scale_x_datetime(breaks = "1 day", date_labels = "%d %b") +
  theme(axis.text.x = element_text(angle = 30, hjust = 1), axis.ticks.x = element_line())
##

max_dt <- max(data_hourly$date_hour)
mid_val <- (max(data_hourly$epa_2021, na.rm=TRUE) - min(data_hourly$epa_2021, na.rm=TRUE))/2

hourly_mm <- data_hourly %>%
# data_hourly %>% 
  group_by(site_id) %>% 
  drop_na(epa_2021) %>% 
  distinct() %>% 
  left_join(data_meta) %>% 
  select(label, site_id, date_hour, epa_2021) %>% 
  mutate(
    extrema = case_when(
      epa_2021 == max(epa_2021, na.rm=TRUE) ~ "max",
      epa_2021 == min(epa_2021, na.rm=TRUE) ~ "min"
    )
  ) %>% 
  drop_na(extrema) %>% 
  pivot_wider(names_from = extrema, values_from = c(epa_2021, date_hour))

data_hourly %>% 
  drop_na(epa_2021) %>% 
  left_join(data_meta) %>% 
  ggplot(aes(x = date_hour, y = epa_2021, group = site_id)) +
  facet_grid(label~.) +
  geom_line(data = data_hourly %>% drop_na(epa_2021), color = "grey") +
  geom_point() +
  geom_point(
    data = . %>% group_by(site_id) %>% filter(epa_2021 == max(epa_2021)) %>% distinct(),
    color = "red"
  ) +
  geom_text(
    data = hourly_mm,
    # data = . %>% group_by(site_id) %>% filter(epa_2021 == max(epa_2021)) %>% distinct(),
    color = "red",
    hjust = "left",
    aes(
      x = max_dt,
      y = mid_val,
      # x = max(data_hourly$date_hour,na.rm=TRUE)+ 12*60*60,
      # y = (max(data_hourly$epa_2021, na.rm=TRUE) - min(data_hourly$epa_2021, na.rm=TRUE))/2,
      label = paste0(
        round(epa_2021_max, digits = 2), " (", format(date_hour_max, "%b %d, %H:%M"), ")\n",
        round(epa_2021_min, digits = 2), "(", format(date_hour_min, "%b %d, %H:%M"), ")"
      )
    )
  ) +
  scale_x_datetime(
    breaks = "1 day",
    expand = expansion(mult = c(0.03, 0.1))
  )
```




```{r}
single_site <- data_hourly %>%
  filter(site_id == "48618823101ce928_2045") %>% 
  select(!c(pm25_cf1_A, pm25_cf1_B, pm25_atm_A, pm25_atm_B, minute)) %>% 
  pivot_longer(cols = c(pm25_cf1, epa_2020, epa_2021, epa_atm, lrapa, pm25_atm),
               names_to = "corr",
               values_to = "pm25") %>% 
  mutate(
    corr = fct_inorder(corr),
    source = fct_collapse(corr,
      PA = c("pm25_cf1", "pm25_atm"),
      EPA = c("epa_2020", "epa_2021", "epa_atm"),
      LRAPA = "lrapa"
    )
  )


single_site %>% 
  ggplot(aes(x = date_hour, y = pm25, color = corr)) +
  facet_grid(source~., scales="free_y") +
  geom_line() +
  theme(legend.position="bottom")

data_diurnal %>% 
  drop_na(epa_2021) %>% 
  #filter(site_id %in% c("48618823101ce928_2045", "a20209a9fb613315_3775", "a0f18656133e64ce_2055")) %>% 
  ggplot(aes(x=hour, y=epa_2021, group=site_id)) +
  geom_path(alpha=0.5) +
  geom_point(shape=1, alpha=0.3)

# data_diurnal %>% 
#   filter(site_id %in% c("48618823101ce928_2045", "a20209a9fb613315_3775", "a0f18656133e64ce_2055")) %>% 
#   drop_na(epa_2021) %>% 
#   ggplot(aes(x=hour,y=epa_2021,group=site_id)) +
#   coord_polar() +
#   geom_path()

data_daily %>% 
  ggplot(aes(x = date, y = epa_2021, group = site_id)) +
  geom_path(alpha=0.5) +
  geom_point(shape = 1, alpha = 0.3)

data_hourly %>% 
  ggplot(aes(x = date_hour, y = epa_2021, group = site_id)) +
  facet_grid(.~date_tag, scales="free") +
  geom_boxplot()
  #geom_point(shape = 1, alpha = 0.5)


single_site %>% 
  filter(corr == "epa_2021") %>% 
  ggplot(aes(x=date,y=hour, fill = pm25)) +
  geom_tile() +
  scale_fill_viridis(name = "Hrly PM25", option = "plasma") +
  facet_grid(.~date_tag, scale="free_x", space="free_x") +
  scale_y_continuous(trans = "reverse", breaks = unique(single_site$hour)) +
  theme_minimal(base_size=8) +
  theme(legend.position="bottom",
        plot.title=element_text(size=14, hjust = 0),
        axis.text.y=element_text(size=6),
        strip.background = element_rect(colour="white"),
        axis.ticks=element_blank(),
        axis.text=element_text(size=7),
        legend.title=element_text(size=8),
        legend.text=element_text(size=6),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        #
        panel.border = element_blank(),
        #panel.background = element_blank(),
        #panel.grid = element_blank(),
        panel.spacing = unit(0,"line")
        )

single_site %>% 
  filter(corr=="epa_2021") %>% 
  ggplot(aes(x = date, y = hour, fill = pm25, label = as.character(sprintf("%.2f", round(pm25, digits=2))))) +
  geom_tile() +
  scale_fill_viridis(option = "plasma", limits = c(0, NA)) +
  #geom_text(aes(color=round(pm25, digits=2)), show.legend=FALSE) +
  #scale_color_viridis(option = "plasma", direction = -1, limits = c(0, NA)) +
  geom_text() +
  scale_y_continuous(trans = "reverse", breaks = 0:23) +
  theme_minimal() +
  theme(
    legend.position = "bottom",
    panel.grid = element_blank()
  )

single_site %>% 
  filter(corr=="epa_2021") %>% 
  ggplot(aes(x=hour, y=pm25, color=as.character(date))) +
  geom_line() +
  theme(legend.position="bottom")

```

```{r}
tenn <- unique(data_meta$site_id)[1:10]

data_hourly %>% 
  filter(site_id %in% tenn) %>% 
  left_join(data_meta) %>% 
  ggplot(aes(x = date_hour, y = epa_2021)) +
  facet_grid(label~.) +
  geom_line()

```

```{r}
#devtools::install_github("hrbrmstr/streamgraph")
library(streamgraph)

data_hourly %>% 
#  filter(site_id %in% tenn) %>% 
  left_join(data_meta) %>% 
  ungroup() %>% 
  column_dt("date") %>% 
  select(label, epa_2021, date_hour, date) %>% 
  streamgraph(key="label",value="epa_2021",date="date_hour") %>% 
  sg_axis_x(1, "date_hour", "%H, %d")

data_daily %>% 
#  filter(site_id %in% tenn) %>% 
  # ungroup() %>% 
  streamgraph("site_id", "epa_2021", "date") %>% 
  sg_axis_x(1, "date", "%d")
```

```{r}
library(ggridges)

data_hourly %>% 
  filter(site_id %in% tenn) %>% 
  ggplot(aes(x = epa_2021, y = site_id, fill = ..x..)) +
  geom_density_ridges_gradient()+
  scale_fill_viridis(option="C")
```

```{r}
single_site %>%
  distinct() %>% 
  ggplot(aes(x = date_hour, y = pm25, color = corr, linetype=source, fill=corr)) +
  #geom_area(alpha=0.4)
  geom_line() +
  geom_point()
```




```{r}
library(leaflet)

site_handful <- data_hourly %>% 
  filter(site_id %in% c("a20209a9fb613315_3775", "48618823101ce928_2045", "a0f18656133e64ce_2055")) %>% 
  select(!c(pm25_cf1_A, pm25_cf1_B, pm25_atm_A, pm25_atm_B, minute)) %>% 
  pivot_longer(cols = c(pm25_cf1, epa_2020, epa_2021, epa_atm, lrapa, pm25_atm),
               names_to = "corr",
               values_to = "pm25") %>% 
  mutate(
    corr = fct_inorder(corr),
    source = fct_collapse(corr,
      PA = c("pm25_cf1", "pm25_atm"),
      EPA = c("epa_2020", "epa_2021", "epa_atm"),
      LRAPA = "lrapa"
    )
  ) %>% 
  left_join(data_meta)

pm_pal <- colorNumeric(palette = "viridis", domain = site_handful$pm25)

leaflet(data=site_handful) %>% 
  addTiles() %>% 
  # addCircles(
  #   data = (site_handful %>% )
  # )
  addCircles(color = ~pm_pal(pm25)) %>% 
  addLayersControl(
    baseGroups = c("Before", "ID", "After")
  )
```

```{r}
library(leaflet)
data_full <- data_daily %>% 
  left_join(data_meta) %>% 
  drop_na(epa_2021) %>% 
  mutate(tag = str_extract(date_tag, ".+(?=\\\n)"))

date_list <- as.character(unique(data_full$date))
loc_list <- unique(data_full$DEVICE_LOCATIONTYPE)
map <- leaflet(data_full) %>% 
  addProviderTiles(providers$CartoDB.DarkMatter)
pal <- colorNumeric(palette = "viridis", domain = data_full$epa_2021)
stroke_pal <- colorFactor(palette = "RdYlBu", domain = data_full$DEVICE_LOCATIONTYPE)

pm_popup <- paste0(data_full$label," (",data_full$latitude,", ",data_full$longitude,")",
                   "<br><b>Location:</b> ", data_full$DEVICE_LOCATIONTYPE,
                  "<br><b>Internal temperature (\u00B0F):</b> ", data_full$temperature,
                  "<br><b>RH (%):</b> ", data_full$humidity,
                  "<br><b>EPA 2020:</b> ", data_full$epa_2020,
                  "<br><b>EPA 2021:</b> ", data_full$epa_2021,
                  "<br><b>LRAPA:</b> ", data_full$lrapa,
                  "<br>(", data_full$tag, ")")

# 
# for (loc_single in loc_list){
#   data_temp <- data_full %>% filter(DEVICE_LOCATIONTYPE == loc_single)

  for (date_single in date_list) {
    data_temp <- data_full %>% filter(date == date_single)

    map <- map %>%
      addCircleMarkers(
        data = data_temp,
        lng = ~longitude,
        lat = ~latitude,
        color = ~stroke_pal(DEVICE_LOCATIONTYPE),
        weight = 1,
        fillColor = ~pal(epa_2021),
        #color = ~pal(epa_2021),
        radius = 5,
        fillOpacity = 0.5,
        #stroke = FALSE,
        #radius = ~sqrt(epa_2021),
        group = date_single,
        label = ~as.character(round(epa_2021, digits=2)),
        popup = pm_popup
      )
  }
# }

# for(date_single in date_list){
#   data_temp <- data_full[data_full$date == date_single,] %>% 
#     filter(DEVICE_LOCATIONTYPE == "outside")
# 
#   map <- map %>%
#     addCircles(
#     #addCircleMarkers(
#       data = data_temp,
#       lng = ~longitude,
#       lat = ~latitude,
#       color = ~pal(epa_2021),
#       radius = 5,
#       fillOpacity = 0.5,
#       #radius = ~sqrt(epa_2021),
#       group = date_single,
#       label = ~as.character(round(epa_2021, digits=2)),
#       popup = pm_popup
#     )
# 
#   #remove(data_temp, date_tag_single, date_tag_list)
# }

map %>%
  addLayersControl(
    baseGroups = date_list,
    #overlayGroups = loc_list,
    options = layersControlOptions(collapsed = FALSE)
  )
```

```{r single_leaflet}
data_full <- data_daily %>% 
  left_join(data_meta) %>% 
  drop_na(epa_2021) %>% 
  mutate(tag = str_extract(date_tag, ".+(?=\\\n)")) %>% 
  filter(date == "2021-07-01")

loc_list <- unique(data_full$DEVICE_LOCATIONTYPE)
map <- leaflet(data_full) %>% 
  addProviderTiles(providers$CartoDB.DarkMatter)
pal <- colorNumeric(palette = "viridis", domain = data_full$epa_2021)

pm_popup <- paste0(data_full$label," (",data_full$latitude,", ",data_full$longitude,")",
                   "<br><b>Location:</b> ", data_full$DEVICE_LOCATIONTYPE,
                  "<br><b>Internal temperature (\u00B0F):</b> ", data_full$temperature,
                  "<br><b>RH (%):</b> ", data_full$humidity,
                  "<br><b>EPA 2020:</b> ", data_full$epa_2020,
                  "<br><b>EPA 2021:</b> ", data_full$epa_2021,
                  "<br><b>LRAPA:</b> ", data_full$lrapa)

# 
# for (loc_single in loc_list){
#   data_temp <- data_full %>% filter(DEVICE_LOCATIONTYPE == loc_single)

  for (loc_single in loc_list) {
    data_temp <- data_full %>% filter(DEVICE_LOCATIONTYPE == loc_single)

    map <- map %>%
      addCircles(
        data = data_temp,
        lng = ~longitude,
        lat = ~latitude,
        # color = "white",
        weight = 20,
        # opacity = 0.1,
        color = ~pal(epa_2021),
        opacity = 0.7,
        # fillColor = ~pal(epa_2021),
        # fillOpacity = 0.5,
        group = loc_single,
        label = ~as.character(round(epa_2021, digits=2)),
        popup = pm_popup
      )
  }

map %>%
  addLayersControl(
    overlayGroups = loc_list,
    options = layersControlOptions(collapsed = FALSE)
  )
```

```{r groups}
library(dplyr)
library(leaflet)
library(htmlwidgets)

data <- data.frame(ID = c("1", "2","3","4","5","6","7","8"),
                   Name = c("A", "A", "A", "B", "B", "C", "C", "C"),
                   Value1 = c(12,43,54,34,23,77,44,22),
                   Value2 = c(6,5,2,7,5,6,4,3),
                   Lat = c(51.1, 51.6, 57.3, 52.4, 56.3, 54.3, 60.4, 49.2),
                   Lon = c(5, -3, -2, -1, 4, 3, -5, 0))
data %>%
  leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addCircles(lat=~Lat, lng=~Lon, radius = ~Value1*1000, group=~Name, label=~Name, popup=~as.character(Value1), layerId = ~paste(ID,"Value1", sep="")) %>%
  addCircles(lat=~Lat, lng=~Lon, radius = ~Value2, group=~Name, label=~Name, popup=~as.character(Value2), layerId = ~paste(ID,"Value2", sep="")) %>%
  addLayersControl(
    baseGroups = c("Value1", "Value2"),
    overlayGroups = c("A", "B", "C"),
    options = layersControlOptions(collapsed = F)
  ) %>%
  htmlwidgets::onRender("
    function(el, x) {
      var myMap = this;
      var baseLayer = 'Value1';
      myMap.eachLayer(function(layer){
        var id = layer.options.layerId;
        if (id){
          if ('Value1' !== id.substring(1,)){
            layer.getElement().style.display = 'none';
          }
        }
      })
      console.log(myMap.baselayer);
      myMap.on('baselayerchange',
        function (e) {
          baseLayer=e.name;
          myMap.eachLayer(function (layer) {
              var id = layer.options.layerId;
              if (id){
                if (e.name !== id.substring(1,)){
                  layer.getElement().style.display = 'none';
                  layer.closePopup();
                }
                if (e.name === id.substring(1,)){
                  layer.getElement().style.display = 'block';
                }
              }

          });
        })
        myMap.on('overlayadd', function(e){
          myMap.eachLayer(function(layer){
            var id = layer.options.layerId;
            if (id){
                if (baseLayer !== id.substring(1,)){
                  layer.getElement().style.display = 'none';
                }
            }    
          })
        })
    }")
```




```{r, viz_time, eval=FALSE}
long_set <- data_hourly %>% 
  pivot_longer(cols = c(pm25_cf1, epa_2020, epa_2021, epa_atm, lrapa, pm25_atm),
               names_to = "corr",
               values_to = "pm25") %>% 
  mutate(
    corr = fct_inorder(corr),
    source = fct_collapse(corr,
      PA = c("pm25_cf1", "pm25_atm"),
      EPA = c("epa_2020", "epa_2021", "epa_atm"),
      LRAPA = "lrapa"
    )
  ) %>% 
  left_join(data_meta) %>% 
  filter(DEVICE_LOCATIONTYPE == "outside",
         pm25 <= 200)

long_set %>% 
  ggplot(aes(date_hour, pm25, color = corr)) +
  facet_wrap(~date_tag, scales = "free") +
  geom_point(alpha = 0.1, shape = 1) +
  stat_smooth() +
  #geom_line()
  theme(legend.position = "bottom")

long_set %>% 
  #ggplot(aes(source, value, color = name)) +
  ggplot(aes(corr, pm25, color = source)) +
  #facet_wrap(~date_tag, scales = "free") +
  facet_wrap(~hour_tag, scales = "free") +
  #facet_wrap(~date_tag) +
  geom_violin(draw_quantiles = c(0.25, 0.5, 0.75), linetype = "dotted") +
  geom_violin(draw_quantiles = 0.5, fill = "transparent") +
  stat_summary(fun.y = mean, geom ="point", color = "red") +
  theme(legend.position = "bottom")

long_set %>% 
  select(!c(pm25_cf1_A,pm25_cf1_B,pm25_atm_A,pm25_atm_B)) %>% 
  mutate(wday = lubridate::wday(date,label=TRUE)) %>% 
  #group_by(site_id, hour, wday, corr, source) %>% 
  group_by(hour, wday, corr, source) %>% 
  summarize_if(is.numeric, mean, na.rm=TRUE) %>% 
  ggplot(aes(x=hour, y=pm25, color=corr)) +
  facet_grid(source~wday, scales="free_y") +
  geom_line() +
  theme(legend.position="bottom")
```

```{r,eval=FALSE}
leveled_meta <- data_meta %>% 
  mutate(label = fct_reorder(as.factor(label), desc(latitude)))
  # arrange(desc(latitude)) %>% 
  # mutate(label = fct_inorder(as.factor(label)))

data_hourly %>% 
  drop_na(epa_2021) %>% 
  left_join(leveled_meta) %>% 
  select(label, date_hour, DEVICE_LOCATIONTYPE, epa_2021) %>% 
  full_join(
    (data_deq %>%
       select(date_hour, pm25_deq) %>%
       mutate(DEVICE_LOCATIONTYPE = "deq", label = "deq") %>%
       rename(epa_2021=pm25_deq) %>% 
       filter(date_hour >= min(data_hourly$date_hour),
              date_hour <= max(data_hourly$date_hour)))
  ) %>% 
  mutate(DEVICE_LOCATIONTYPE = factor(DEVICE_LOCATIONTYPE, levels = c("inside", "deq", "outside"))) %>% 
  ggplot(aes(x = date_hour, y = label, fill = epa_2021)) +
  facet_grid(DEVICE_LOCATIONTYPE~., scales="free_y", space="free_y") +
  geom_tile() +
  scale_fill_viridis(option="plasma", limits=c(0, 50))
```

```{r}
library(GGally)

ggparcoord(iris, columns=1:4, groupColumn=5)
ggparcoord(iris, columns=1:4, groupColumn="Species")

data_daily %>% 
  #left_join((data_meta %>% group_by(DEVICE_LOCATIONTYPE) %>% slice(1:20))) %>% 
  left_join(data_meta) %>% 
  drop_na(label) %>% 
  select(site_id, date, epa_2021, DEVICE_LOCATIONTYPE) %>% 
  drop_na(epa_2021) %>% 
  distinct() %>% 
  pivot_wider(names_from = date, values_from = epa_2021) %>% 
  ggparcoord(columns = 3:7, groupColumn = "DEVICE_LOCATIONTYPE", scale = "center")
```

```{r}
data_hourly %>% 
  column_dt(c("hour", "date")) %>% 
  ungroup() %>% 
  group_by(hour, date) %>% 
  summarize(pm = mean(epa_2021, na.rm=TRUE)) %>% 
  ggplot(aes(x = hour, y = pm, color = date, group = date)) +
  geom_line()

data_daily %>% 
  select(date, epa_2021) %>% 
  ggplot(aes(x = epa_2021)) +
  facet_wrap(~date) +
  geom_histogram(binwidth = 1)

high_ids <- raw_meta %>%
  select(site_id, flag_highValue) %>%
  filter(flag_highValue == TRUE) %>% 
  pull(site_id)

data_hourly %>% 
  select(site_id, date_hour, epa_2021) %>% 
  rename(pm = epa_2021) %>% 
  rbind((data_deq %>% select(site_id, date_hour, pm25_deq) %>% rename(pm = pm25_deq))) %>% 
  filter(!site_id %in% high_ids) %>% 
  left_join(data_meta) %>% 
  select(site_id, date_hour, pm, DEVICE_LOCATIONTYPE) %>% 
  mutate()
  # left_join((data_meta %>% select(site_id, DEVICE_LOCATIONTYPE))) %>% 
  # left_join((data_deq_meta %>% select(site_id, DEVICE_LOCATIONTYPE)), by = "site_id")

data_hourly %>% 
  drop_na(epa_2021) %>% 
  filter(!site_id %in% high_ids) %>% 
  left_join(data_meta) %>% 
  ggplot(aes(x = date_hour, y = epa_2021, color = DEVICE_LOCATIONTYPE, shape = DEVICE_LOCATIONTYPE, alpha = DEVICE_LOCATIONTYPE)) +
  geom_point(size = 2) +
  scale_alpha_manual(values = c("outside" = 0.1, "inside" = 0.5, "DEQ" = 1.0)) +
  scale_shape_manual(values = c("outside" = 16, "inside" = 18, "DEQ" = 17)) +
  theme_bw() +
  theme(legend.position = "bottom") +
  guides(alpha = "none")

data_hourly %>% 
  drop_na(epa_2021) %>% 
  filter(!site_id %in% high_ids) %>% 
  column_dt(c("date", "hour")) %>% 
  left_join(data_meta) %>% 
  ggplot(aes(x = hour, y = epa_2021, color = date, group = date)) +
  geom_line()
```



```{r,eval=FALSE}
ggplot(data_daily, aes(x = date, y = epa_2021, group = date)) +
  geom_violin() + 
  geom_jitter(alpha = 0.1)

data_daily %>% 
  left_join((data_meta %>% group_by(DEVICE_LOCATIONTYPE) %>% slice(1:20))) %>% 
  drop_na(label) %>% 
  # mutate(date = as.character(date)) %>% 
  #filter(str_detect(label, "rd Drive")) %>% 
  ggplot(aes(x = date, y = epa_2021, group = date)) +
  facet_grid(DEVICE_LOCATIONTYPE~.) +
  geom_boxplot()

data_hourly %>% 
  left_join((data_meta %>% group_by(DEVICE_LOCATIONTYPE) %>% slice(1:20))) %>% 
  drop_na(DEVICE_LOCATIONTYPE) %>% 
  column_dt(c("date", "hour")) %>% 
  ggplot(aes(x = hour, y = epa_2021, group = site_id)) +
  facet_grid(date~DEVICE_LOCATIONTYPE) +
  geom_point()

data_hourly %>% 
  left_join((data_meta %>% filter(str_detect(label,"rd Drive")))) %>% 
  drop_na(label) %>% 
  ggplot(aes(x = hour, y = epa_2021, color = date, group = date)) +
  geom_line()

data_daily %>% 
  left_join((data_meta %>% group_by(DEVICE_LOCATIONTYPE) %>% slice(1:10))) %>% 
  drop_na(label) %>% 
  mutate(date = day(date)) %>% 
  streamgraph(
    key="site_id",
    value="epa_2021",
    date="date",
    scale = "continuous"
  )
  # sg_axis_x(5,tick_units="day")

library(highcharter)
data_hourly %>% 
  filter(epa_2021 <= 200, str_detect(date_tag, "Before"), site_id %in% (data_meta %>% slice(1:10) %>% pull(site_id))) %>% 
  left_join(data_meta) %>% 
  # left_join((data_meta %>% group_by(DEVICE_LOCATIONTYPE) %>% slice(1:10))) %>%
  # drop_na(label) %>%
  hchart("streamgraph", hcaes(date_hour, epa_2021, group=label))
```

