---
title: "summer_mapping"
author: "Gillian McGinnis"
date: "6/21/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

input_path_filter <- "*SE*"
source(knitr::purl("R/summer_wrangle.Rmd"))
file.remove("summer_wrangle.R")
remove(data_secondary, file_list, clean_data, list = ls(pattern = "input_"))

source(knitr::purl("R/summer_epa.Rmd"))
file.remove("summer_epa.R")

library(ggmap)
library(lubridate)
library(viridis)
```


```{r apply_dates_set}
apply_dates <- function(dataset, starts, ends, tags){
  
  starts <- as.Date(starts)
  ends <- as.Date(ends)
  tags <- factor(tags)
  
  data_temp <- data.frame(starts, ends, tags) %>% 
    arrange(starts) %>% 
    mutate(date_tag = fct_inorder(tags)) %>% 
    pivot_longer(cols = c(starts, ends), values_to = "date") %>% 
    group_by(date_tag) %>% 
    complete(date = full_seq(date, 1)) %>% 
    select(!c(name, tags))
  
  dataset %>% 
    left_join(data_temp) %>% 
    drop_na(date_tag)
}

data_dated <- apply_dates(data_corr,
                          c("2020-09-01", "2020-09-10", "2020-09-20"),
                          c("2020-09-09", "2020-09-19", "2020-09-29"),
                          c("Pre", "Fire", "Post"))
```

```{r apply_dates_grouped}
# apply_date_averages <- function(dataset, time){
#   # dataset %>% 
#   #   mutate(num = {{time}}(date_time))
# }
# 
# apply_date_averages(data_primary, hour)
# 
# data_primary %>% 
#   slice(1:1000) %>% 
#   mutate(
#     date = date(date_time),
#     year = year(date_time),
#     month = month(date_time),
#     day = day(date_time),
#     time = time(date_time),
#     hour = hour(date_time),
#     minute = minute(date_time),
#     second = second(date_time)
#   ) %>% 
#   group_by() %>% 
#   head()
```



```{r map_function}
lab_pm <- expression(paste("Average PM"[2.5]*" (", mu, "g/m"^3*"):"))
lab_inout <- paste("Location:")

map_q <- function(dataset, correction = epa_2021,
                  maptype = "toner-lite", zoom = 11, darken = 0.5, darken_color = "black"){
  data_temp <- dataset %>% 
    ungroup() %>% 
    group_by(loc_tag, date_tag) %>% 
    summarize(mean = mean({{correction}}, na.rm=TRUE)) %>% 
    left_join(data_loc)
  
  qmplot(data = data_temp, x = lon, y = lat, geom = "blank", maptype = maptype, zoom = zoom, darken = c(darken, darken_color)) +
    facet_wrap(~date_tag) +
    geom_point(aes(size = mean, fill = mean, shape = loc_inout), color = "white", alpha = 0.7) +
    scale_fill_viridis(option = "magma", begin = 0.2, end = 0.9, direction = -1) +
    scale_size_continuous() +
    scale_shape_manual(values = c("outside" = 21, "inside" = 23)) +
    guides(fill = guide_legend(), size = guide_legend()) +
    theme_void() +
    theme(
      legend.position = "bottom",
      legend.box = "vertical"
    ) +
    labs(
      fill = lab_pm,
      size = lab_pm,
      shape = lab_inout
    )
}

map_q(data_dated, correction = epa_2020)
```

```{r function_grab_map, eval = FALSE}
grab_map <- function(bottom, top, left, right, maptype = "toner-lite", zoom = 11, crop = TRUE){
  coord_box <- c(bottom = bottom, top = top, left = left, right = right)
  data_map <- get_stamenmap(coord_box, maptype = maptype, zoom = zoom, crop = crop)
}

pdx_map <- grab_map(45.5, 45.6, -122.854, -122.58, "toner-lite")

ggmap(pdx_map)
```

```{r map_grab, eval = FALSE}
grab_map_auto <- function(location_df, maptype = "toner-lite", adj = 0.03, zoom = 11, crop = TRUE){
  location_df %>% 
    ungroup() %>% 
    summarize(
      left = min(lon)-adj,
      bottom = min(lat)-adj,
      right = max(lon)+adj,
      top = max(lat)+adj
    ) %>% 
    as.numeric() %>% 
    get_stamenmap(maptype = maptype, zoom = zoom, crop = crop)
}

grab_map_auto(data_loc, maptype = "toner-lite") %>% ggmap(darken = 0.7) + geom_point(data = data_loc, aes(color = "red"))
```

```{r apply_dates_manual, eval = FALSE}
input_date_starts <- as.Date(c("2020-09-01", "2020-09-10", "2020-09-20"))
input_date_ends <- as.Date(c("2020-09-09", "2020-09-19", "2020-09-29"))
input_date_tags <- factor(c("Pre", "Fire", "Post"))

data_dates <- data.frame(
  input_date_starts, input_date_ends, input_date_tags
) %>% 
  arrange(input_date_starts) %>% 
  mutate(date_tag = fct_inorder(input_date_tags)) %>% 
  pivot_longer(cols = c(input_date_starts, input_date_ends), values_to = "date") %>% 
  group_by(date_tag) %>% 
  complete(date = full_seq(date, 1)) %>%
  select(!c(name, input_date_tags))

data_dated <- data_corr %>% 
  left_join(data_dates) %>% 
  drop_na(date_tag)

remove(data_dates, list = ls(pattern = "input_"))
```


```{r mapping_manual, eval = FALSE}
data_mapping <- data_dated %>% 
  group_by(loc_tag, date_tag) %>% 
  summarize(epa_2021 = mean(epa_2021, na.rm = TRUE)) %>% 
  left_join(data_loc)

pdx_map %>% 
  ggmap() +
  facet_wrap(~date_tag) +
  geom_point(data = data_mapping, aes(size = epa_2021, color = epa_2021, shape = loc_inout)) +
  scale_color_viridis(option = "magma", begin = 0.2, end = 0.9, direction = -1) +
  scale_size_continuous() +
  theme_void() +
  guides(color = guide_legend(), size = guide_legend()) +
  theme(legend.position = "bottom")
```

```{r map_partly_functioned, eval = FALSE}
map_full <- function(input_data, input_map, correction = epa_2021){
  data_temp <- input_data %>% 
    group_by(loc_tag, date_tag) %>% 
    summarize(mean = mean({{correction}}, na.rm=TRUE)) %>% 
    left_join(data_loc)
  
  input_map %>% 
    ggmap() +
    facet_wrap(~date_tag) +
    geom_point(data = data_temp, aes(size = mean, color = mean, shape = loc_inout)) +
    scale_color_viridis(option = "magma", begin = 0.2, end = 0.9, direction = -1) +
    scale_size_continuous() +
    guides(color = guide_legend(), size = guide_legend()) +
    theme_void() +
    theme(
      legend.position = "bottom",
      legend.box = "vertical"
    )
}

map_full(data_dated, pdx_map, correction = epa_2021)
```

```{r map_function, eval = FALSE}
map_q <- function(pm_data, value, grouping_var = NULL, exclude = NULL, location_data = data_meta,
                  maptype = "toner-lite", zoom = 11, tint = 0.5, tint_color = "black",
                  point_size = 3, viridis = "viridis"){
  
  data_temp <- pm_data %>% 
    ungroup() %>% 
    group_by_at(vars(site_id, {{grouping_var}})) %>% 
    summarize(mean = mean({{value}}, na.rm = TRUE)) %>% 
    drop_na(mean) %>% 
    left_join(location_data)
  
  
  to_exclude <- paste(exclude, collapse = "|")
  
  if(is.null(exclude) == FALSE){
    data_temp <- data_temp %>% 
      filter(!str_detect({{grouping_var}}, to_exclude))
  }
  
  # Labels for map
  lab_pm <- expression(paste("Average PM"[2.5]*" (", mu, "g/m"^3*"):"))
  lab_caption <- paste("Data grouped by:", (colnames(pm_data %>% select({{grouping_var}})))[1])
  
  qmplot(data = data_temp, x = longitude, y = latitude,
         geom = "blank", maptype = maptype, zoom = zoom, darken = c(tint, tint_color)) +
    facet_wrap(vars({{grouping_var}})) +
    geom_point(
      aes(
        #size = mean,
        #shape = DEVICE_LOCATIONTYPE,
        fill = mean
      ),
      color = "white",
      alpha = 0.85,
      size = point_size,
      shape = 21
    ) +
    #scale_fill_viridis(option = {{viridis}}, direction = -1, end = 0.85) +
    scale_fill_viridis(
      option = {{viridis}},
      direction = -1,
      end = 0.85,
      limits = c(0, NA)
    ) +
    #scale_size_continuous() +
    #scale_shape_manual(values = c("outside" = 21, "inside" = 23)) +
    #guides(fill = guide_legend(), size = guide_legend()) +
    theme_void() +
    theme(
      legend.position = "bottom",
      legend.box = "vertical"
    ) +
    # guides(
    #   fill = guide_colorbar(
    #     barwidth = 10,
    #     barheight = 0.5,
    #     
    #   )
    # )+
    labs(
      #size = lab_pm,
      #shape = lab_inout,
      fill = lab_pm,
      caption = lab_caption
    )
}
```

```{r map_tests, eval = FALSE}
map_q(data_daily, value = epa_2021, grouping_var = date_tag)
map_q(data_hourly, value = lrapa, grouping_var = hour_tag, exclude = "Afternoon")
map_q(data_daily, value = lrapa, grouping_var = date_tag, exclude = "Fire")

map_q(data_hourly, value = lrapa, grouping_var = hour_tag, exclude = "Afternoon", point_size = 5,
      maptype = "terrain", tint = 0.3, tint_color = "orange", viridis = "magma")
```

```{r function_testing, eval = FALSE}
testing_function <- function(first_var, second_var = NULL){
  plot <- diamonds %>% 
    filter(color == "E") %>% 
    ggplot(aes(price, depth)) +
    geom_point()
  
  if(deparse(substitute(first_var)) != "NULL" &
     deparse(substitute(second_var)) == "NULL"
    ){
    plot <- plot +
      facet_wrap(vars({{first_var}}))
  }
  
  if(deparse(substitute(second_var)) != "NULL" &
     deparse(substitute(second_var)) != "NULL"
     ){
    plot <- plot +
      facet_grid(
      formula(paste(
        vars({{first_var}}),
        "~",
        vars({{second_var}})
      ))
    )
  }
  plot
}
testing_function(clarity)
testing_function(clarity, cut)


map_testing <- function(pm_data, value, grouping_var = NULL, exclude = NULL,
                        location_data = data_meta,
                  maptype = "toner-lite", zoom = 11, tint = 0.5, tint_color = "black",
                  point_size = 3, viridis = "viridis",
                  grouping_var_2 = NULL, exclude_2 = NULL){
  
  data_temp <- pm_data %>% 
    ungroup() %>% 
    group_by_at(vars(site_id, {{grouping_var}}, {{grouping_var_2}})) %>% 
    summarize(mean = mean({{value}}, na.rm = TRUE)) %>% 
    drop_na(mean) %>% 
    left_join(location_data)
  
  
  if(is.null(exclude) == FALSE){
    to_exclude <- paste(exclude, collapse = "|")
    
    data_temp <- data_temp %>% 
      filter(!str_detect({{grouping_var}}, to_exclude))
  }
  if(is.null(exclude_2) == FALSE){
    to_exclude_2 <- paste(exclude_2, collapse = "|")
    
    data_temp <- data_temp %>% 
      filter(!str_detect({{grouping_var_2}}, to_exclude_2))
  }
  
  # Labels for map
  lab_pm <- expression(paste("Average PM"[2.5]*" (", mu, "g/m"^3*"):"))
  #deparse(substitute(second_var)) != "NULL"
  # if(deparse(substitute(grouping_var)) != "NULL" & deparse(substitute(grouping_var_2)) == "NULL"){
  #   lab_caption <- paste("Data grouped by:",
  #                        (colnames(pm_data %>% select({{grouping_var}})))[1]
  #                        )
  # }
  # if(deparse(substitute(grouping_var)) != "NULL" & deparse(substitute(grouping_var_2)) != "NULL"){
  #   lab_caption <- paste("Data grouped by:",
  #                        (colnames(pm_data %>% select({{grouping_var}})))[1],
  #                        "&",
  #                        (colnames(pm_data %>% select({{grouping_var_2}})))[1]
  #                        )
  # }
  # if(deparse(substitute(grouping_var)) == "NULL" & deparse(substitute(grouping_var_2)) == "NULL"){
  #   lab_caption <- "Data not grouped."
  # }
  
  plot <- qmplot(data = data_temp, x = longitude, y = latitude,
         geom = "blank", maptype = maptype, zoom = zoom, darken = c(tint, tint_color)) +
    #facet_wrap(vars({{grouping_var}}, {{grouping_var_2}})) +
    geom_point(
      aes(
        fill = mean
      ),
      color = "white",
      alpha = 0.85,
      size = point_size,
      shape = 21
    ) +
    scale_fill_viridis(
      option = {{viridis}},
      direction = -1,
      end = 0.85,
      limits = c(0, NA)
    ) +
    theme_void() +
    theme(
      legend.position = "bottom",
      legend.box = "vertical"
    ) +
    labs(
      caption = "Data not grouped."
    )
  
  if(deparse(substitute(grouping_var)) != "NULL" &
     deparse(substitute(grouping_var_2)) == "NULL"
    ){
    plot <- plot +
      facet_wrap(vars({{grouping_var}})) +
      labs(
        caption = paste(
          "Data grouped by:",
          (colnames(pm_data %>% select({{grouping_var}})))[1]
        )
      )
  }
  
  if(deparse(substitute(grouping_var)) != "NULL" &
     deparse(substitute(grouping_var_2)) != "NULL"
     ){
    plot <- plot +
      facet_grid(
      formula(paste(
        vars({{grouping_var}}),
        "~",
        vars({{grouping_var_2}})
      ))) +
      labs(
        caption = paste(
          "Data grouped by:",
          (colnames(pm_data %>% select({{grouping_var}})))[1],
          "&",
          (colnames(pm_data %>% select({{grouping_var_2}})))[1]
          )
      )
  }
  plot
}

map_testing(pm_data = data_hourly, value = lrapa, grouping_var = date_tag, grouping_var_2 = hour_tag)
map_testing(pm_data = data_hourly, value = lrapa, grouping_var = hour_tag, grouping_var_2 = date_tag)
map_testing(pm_data = data_hourly, value = lrapa, grouping_var = date_tag, exclude = "Before")

map_testing(pm_data = data_hourly, value = lrapa, grouping_var = date_tag)
map_testing(pm_data = data_hourly, value = lrapa)
```



