---
title: "summer_deq"
author: "Gillian McGinnis"
date: "6/17/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(tidyverse)
library(readxl)
library(lubridate)
```


```{r inputs}
input_deq_path <- "data/deq/SEL_july.xlsx"
```

```{r se_laf_loc}
# The following is location data for the DEQ FRM in Portland
data_deq_meta <- data.frame(
  label = "DEQ SE Lafayette",
  DEVICE_LOCATIONTYPE = factor("DEQ"), # The device is outside but this will label it separately
  latitude = 45.496641,
  longitude = -122.602877,
  site_id = "41-051-0080",
  timezone = "America/Los_Angeles"
)
```


```{r settings}
# Input of renames. Those listed will be included in the final data frame.
# Time stamp will be automatically renamed and kept.
input_deq_renames <- c(
  "PM2.5" = "pm25_deq",
  "Temperature" = "temperature_c",
  "Relative Humidity" = "humidity",
  "Wind Direction" = "wind_direction",
  "Wind Speed (mph)" = "wind_speed",
  "Black Carbon (BC6 880nm)" = "black_carbon"
)
```


```{r data_import}

# Creating a list of variable names
deq_names <- read_excel(input_deq_path,
                             sheet = 1, # Selecting sheet 1
                             skip = 2, # Skipping the empty rows at the top
                             n_max = 0) %>% names() # Selecting 0 observations, and extracting the names only

# All DEQ data aside from time stamps is numeric
# To avoid R from identifying columns with lots of missing data as logical, all columns except date time are set to numeric:
deq_coltypes <- ifelse(grepl("Date Time", deq_names), "text", "numeric")

# Creating a data frame of the data
raw_deq <- read_excel(input_deq_path,
                           sheet = 1, # Selecting sheet 1
                           skip = 4, # Skipping the topmost rows naming the variables, etc
                           na = "----", # NAs are reported using this symbol in the Excel file
                           col_names = deq_names, # Setting column names to be those listed above
                           col_types = deq_coltypes) # Setting column types

# Data frame of units, for reference if needed.
deq_units <- read_excel(input_deq_path,
                        sheet = 1, # Selecting sheet 1
                        skip = 2, # Skipping the empty rows at the top
                        n_max = 1) # Selecting 1 "observation" (next row)
```

```{r eclean_read}
remove(deq_names, deq_coltypes, deq_units, input_deq_path)
```


```{r data_wrangling}
data_deq <- raw_deq %>% 
  mutate(
    # DEQ reports time stamps in Pacific Standard Time, meaning DST is NOT accounted for.
    # Using Etc/GMT+8 here will mark the time stamps as the appropriate -8 ("PST")
    datetime_standard = parse_date_time(`Date Time`, "%H:%M %m/%d/%Y", tz = "Etc/GMT+8"),
    # The following will adjust time stamps for DST appropriately:
    `Date Time` = with_tz(datetime_standard, tzone = "America/Los_Angeles")
  ) %>% 
  rename(date_hour = `Date Time`) %>% 
  # Renaming variables based on inputs at the top
  plyr::rename(warn_missing = FALSE, input_deq_renames) %>% 
  mutate(site_id = data_deq_meta$site_id) %>% 
  # Selecting only renamed variables in addition to time stamps
  select(c(site_id, date_hour, intersect(all_of(input_deq_renames), names(.)), datetime_standard))

# Converting deg Ç (units in which DEQ reports) to deg F (units in which PA reports)
if ("temperature_c" %in% colnames(data_deq) == TRUE) {
  data_deq <- data_deq %>% 
    mutate("temperature" = (temperature_c*(9/5))+32)
}
```

```{r eclean_wrangle}
remove(input_deq_renames)
```
